/**
 * AuxDevice Class
 * 
 * Creates a simulation of an auxilary device which generates power.
 * 
 * @author Marc Reinhardt
 * @version 0.3
 */

package AuxDevice;

public class AuxDevice
{
    
    private SignedGenerated generated;
    
    /**
     * AuxDevice Constructor
     */
    public AuxDevice(){
        generated = new SignedGenerated(6,155);
    }
     
    /**
     * Method signatureTest
     * Creates an invalid signature for testing purposes
     */
    public void signatureTest(){
        generated = new SignedGenerated(99,123123);
    }
    
    /**
     * Method updateGenerated
     * Returns the current power generated by the device
     */
    public  SignedGenerated updateGenerated(){
        return generated;
    }
  
}